source_recursive() {
	local DIRECTORY=${1%/}
	local GLOB=${2}

	if [ -d "${DIRECTORY}" ]; then
		setopt GLOB_SUBST
		FILES=("${DIRECTORY}"/${GLOB})
		unsetopt GLOB_SUBST

		for FILE in ${FILES}; do
			if [ -e "${FILE}" ]; then
				source "${FILE}"
			fi
		done
	fi
}

SCRIPT_DIR="$(dirname -- "$(readlink -f -- "${(%):-%N}")")"
export DOTFILES="$(readlink -f -- "${SCRIPT_DIR}/..")"

source_recursive "${SCRIPT_DIR}/rc.d/" '*.sh'
source_recursive "${SCRIPT_DIR}/zshrc.d/" '*.zsh'
