#!/bin/zsh
# shellcheck shell=bash
# shellcheck disable=SC1090,SC1091,SC2296

# Powerlevel10k Instant Prompt
if [[ -r "${XDG_CACHE_HOME:-${HOME}/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Common Shell Configuration
# shellcheck source=dot_shell/common.sh.tmpl
source "${HOME}/.shell/common.sh"

# Powerlevel10k Shell Theme
[[ ! -f "${HOME}/.p10k.zsh" ]] || source "${HOME}/.p10k.zsh"
source "${HOME}/.plugins/powerlevel10k/powerlevel10k.zsh-theme"
