#!/bin/sh

# Launch scripts in /etc/X11/xinit/xinitrc.d
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# Set X11 keyboard map
setxkbmap eu

# Merge Xresources
xrdb -merge -I "$HOME" ~/.Xresources

# Change x11 root cursor
xsetroot -cursor_name left_ptr

# Launch urxvt terminal daemon
urxvtd -q -f -o

# Launch redshift to reduce eye strain
redshift &

# Start compton compositor
compton --config ~/.config/compton/config &

# Launch wallpaper script
~/.local/bin/wallpaper.sh &

# Start bspwm
exec bspwm
