#!/bin/sh

# Launch scripts in /etc/X11/xinit/xinitrc.d
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# Set X11 keyboard map
setxkbmap eu

# Merge Xresources
xrdb -merge -I "$HOME" ~/.Xresources

# Change x11 root cursor
xsetroot -cursor_name left_ptr

# Launch redshift to reduce eye strain
redshift &

# Launch unclutter to hide mouse after inactivity
unclutter &

# Launch compton compositor
compton --config ~/.config/compton/config &

# Launch desktop environment scripts
~/.local/scripts/de-wallpaper.sh &
~/.local/scripts/de-polybar.sh &

# Launch hotkey daemon
sxhkd &

# Start bspwm
exec bspwm
