#! /bin/sh
sxhkd &

bspc monitor DisplayPort-0 -d I II III
bspc monitor DisplayPort-1 -d IV V VI
bspc monitor DisplayPort-2 -d VII VIII IV V

bspc config border_width 1
bspc config window_gap 12
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config super mod4
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner
bspc config click_to_focus true
bspc config presel_feedback_color \#aaaaaa

bspc desktop ^1 -l monocle
bspc desktop ^9 -l monocle
bspc desktop ^10 -l monocle

bspc rule -a Chromium desktop=^1
bspc rule -a Firefox desktop=^1
bspc rule -a URxvt:profanity desktop=^3
bspc rule -a xfreerdp desktop=^9 state=tiled locked=true private=true
bspc rule -a keepass2 desktop=^10 state=tiled locked=true private=true

xsetroot -cursor_name left_ptr
xrdb -merge ~/.Xresources
~/.local/bin/wallpaper.sh
redshift &
MONITOR=DisplayPort-0 polybar side &
MONITOR=DisplayPort-1 polybar main &
MONITOR=DisplayPort-2 polybar side &
compton --config ~/.config/compton/config &
