export PATH="${DOT}/bin:${HOME}/.cabal/bin:${HOME}/.ghcup/bin:${HOME}/.cargo/bin:${HOME}/go/bin:${HOME}/.npm/bin:${PATH}"
export EDITOR="$(command -v vim)"
export PYTHONIOENCODING="UTF-8"
export MANPAGER="less -X"
export NVM_DIR="${HOME}/.nvm"
export GOPATH="${HOME}/go"
export GOPROXY="proxy.golang.org,direct"
